### ISSUE TITLE
Creare a JSON con gli indici del grafo iniziale

### ISSUE THREAD

**Issue by simCecca** [simCecca/Big-Graph-Drawing#1]
- [x] I vertici che sono nel jSON che tira fuori il server, devono comparire con l'id iniziale (quello che hanno nel GML)
      

- [x] Studiare i metodi di OGDF per passare da un nodo del BC-Tree al corrispettivo della componente connessa 
        corrispondente 
         in teoria si fa con il metodo original() che prende in ingresso un oggetto di tipo nodo però che sia vH quindi della terza 
         struttura della documentazione di OGDF.
        CONSIDERAZIONE: i vertici di taglio appartengono alla struttura dati due della documentazione di OGDF quindi non 
        sono di tipo vH ma vB quindi vedere come si può passare da un vertice di taglio al corrispondente nodo della CC; io 
        ricordo che nel codice faccio così: prendo un vertice di taglio, mi faccio dare il corrispondente in uno del blocchi a cui 
        è connesso e poi chiamo original(quest'ultimo nodo)

- [x] Studiare come passare da un nodo della CC ad uno del grafo originale

- [x] Verificare se stiamo utilizzando gli id del grafo iniziale all'interno delle componenti connesse. e se non li stiamo utilizzando convertirli a quelli del grafo iniziale, poi fare la stessa cosa per i vertici di taglio

**Comment by DavideCoppola** [comment]
Tuti i punti di tale story sono stati effettuati e completati
