### ISSUE TITLE
Verifica dpcumentazione BC-Tree 

### ISSUE THREAD

**Issue by simCecca** [simCecca/Big-Graph-Drawing#3]
- [x] Verificare se è possibile creare un BC-Tree con un grafo che ha più componenti connesse

Quindi, prendi un grafo con più componenti connesse, crei un nuovo progetto, crei un oggetto di tipo bc-tree con questo grafo e vedi se scoppia

**Comment by DavideCoppola** [comment]
Parte nn implementata per impossibilità di lavoro con tali strutture
