### ISSUE TITLE
woleMaxSize

### ISSUE THREAD

**Issue by simCecca** [simCecca/Big-Graph-Drawing#6]
woleMaxSize non ritorna il totale degli archi contenuti in tutto il grafo, ma sembra il max blocco della cc più grande.

- [x] vedere il perchè e fixare

**Comment by DavideCoppola** [comment]
In effetti woleMaxSize riprende il blocco più grande (in termini di num di archi) della cc più grande, e sembra proprio fatto per comportarsi così.
